dist: xenial

language: python
python:
  - "3.6"

branches:
  only:
    - buidling
    - develop
    - master

before_install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update -q
  - sudo apt-get install flatpak flatpak-builder

before_script:
  # Install dependencies of 'pipenv_flatpak.py'
  - travis_retry pip3 install requests html5lib
  # Set some variables
  - export BUILD_BRANCH=$TRAVIS_BRANCH
  - export BUILD_COMMIT=$TRAVIS_COMMIT

script:
  - cd scripts/Flatpak          # Enter the flatpak directory
  - ./build_flatpak.sh          # Run the build
  - cd $TRAVIS_BUILD_DIR        # Return into build directory

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/scripts/Flatpak/.flatpak-builder

before_deploy:
  # Generate the bintray.json manifest
  - python3 scripts/travis_bintray.py

deploy:
  provider: bintray
  file: scripts/bintray.json
  user: "francescoceruti"
  key: $BINTRAY_API_KEY
  skip_cleanup: true # since we are building inside the working-directory
  on:
    all_branches: true
