# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - develop
        - building

    machine: true

    working_directory: ~/repo

    environment:
      BUILD_BRANCH: $CIRCLE_BRANCH
      BUILD_COMMIT: $CIRCLE_SHA1

    steps:
      - checkout

      - run:
          name: DOCKER ⟹ pull
          command: |
            docker pull flatpak/flatpak-builder:base

      - run:
          name: DOCKER ⟹ run
          working_directory: ~/repo/scripts/Flatpak
          command: |
            docker run --privileged --volume ${PWD}:/tmp/build --name fb -it -d flatpak/flatpak-builder:base /bin/bash
            docker exec -it fb bash -c "export BUILD_BRANCH=$BUILD_BRANCH && export BUILD_COMMIT=$BUILD_COMMIT"

      - run:
          name: Install flathub Runtime & SDK
          command: |
            docker exec -it fb bash -c 'cd /tmp/build/ && source functions.sh && flatpak_install_runtime'

      - restore_cache:
          keys:
            - v1-pip-{{ checksum "scripts/Flatpak/requirements.txt" }}

      - run:
          name: MACHINE ⟹ Generate flatpak manifest
          working_directory: ~/repo/scripts/Flatpak
          command: source functions.sh && flatpak_build_manifest

      - save_cache:
          key: v1-pip-{{ checksum "scripts/Flatpak/requirements.txt" }}
          paths:
            - ./venv

      - restore_cache:
          keys:
            - v1-flatpak-{{ checksum "scripts/Flatpak/com.github.FrancescoCeruti.LinuxShowPlayer.json" }}
            - v1-flatpak-

      - run:
          name: DOCKER ⟹ Build flatpak
          command: docker exec -it fb bash -c 'cd /tmp/build/ && source functions.sh && flatpak_build'

      - save_cache:
          key: v1-flatpak-{{ checksum "scripts/Flatpak/com.github.FrancescoCeruti.LinuxShowPlayer.json" }}
          paths:
            - /tmp/build/.flatpak-builder

      - run:
          name: DOCKER ⟹ Bundle flatpak
          command: docker exec -it fb bash -c 'cd /tmp/build/ && source functions.sh && flatpak_bundle'

      - store_artifacts:
          path: /tmp/build/out
          destination: build